[project]
name = "viki_ai"
version = "0.1.0"
description = "VIKI - Open Agent Platform"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.1.0",
    "sqlalchemy>=2.0.41",
]
